import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        syne: ["Lato", "sans-serif"],
        "dm-sans": ["Lato", "sans-serif"],
        "dm-mono": ["Lato", "sans-serif"],
        lato: ["Lato", "sans-serif"],
      },
      colors: {
        navy: "#1B3A6B",
        "blue-accent": "#2E6BE6",
        "blue-light": "#EBF0FC",
        "blue-mid": "#C4D4F8",
        "page-bg": "#F7F8FC",
        "card-bg": "#FFFFFF",
        border: "#E8EBF2",
        "border-mid": "#D0D6E8",
        "text-primary": "#0D1C3A",
        "text-secondary": "#6A7590",
        "text-muted": "#A0AABB",
        background: "#F7F8FC",
        foreground: "#0D1C3A",
        card: "#FFFFFF",
        "card-foreground": "#0D1C3A",
        popover: "#FFFFFF",
        "popover-foreground": "#0D1C3A",
        primary: "#1B3A6B",
        "primary-foreground": "#FFFFFF",
        secondary: "#EBF0FC",
        "secondary-foreground": "#0D1C3A",
        muted: "#D0D6E8",
        "muted-foreground": "#6A7590",
        accent: "#2E6BE6",
        "accent-foreground": "#FFFFFF",
        destructive: "#DC2626",
        "destructive-foreground": "#FFFFFF",
        input: "#FFFFFF",
        ring: "#2E6BE6",
        "chart-1": "#1B3A6B",
        "chart-2": "#2E6BE6",
        "chart-3": "#C4D4F8",
        "chart-4": "#A9B4E3",
        "chart-5": "#8DA3C9",
        sidebar: "#F7F8FC",
        "sidebar-foreground": "#0D1C3A",
        "sidebar-primary": "#1B3A6B",
        "sidebar-primary-foreground": "#FFFFFF",
        "sidebar-accent": "#EBF0FC",
        "sidebar-accent-foreground": "#0D1C3A",
        "sidebar-border": "#E8EBF2",
        "sidebar-ring": "#2E6BE6",
      },
    },
  },
  plugins: [],
};
export default config;
