export const POLICY_JSON_DB = [
  {
    id: "aetna-humira",
    payer_id: "aetna",
    drug_name: "Humira",
    coverage_status: "covered",
    policy_version: "v1",
    effective_date: "2026-04-01",
    prior_auth_required: true,
    step_therapy: true,
    quantity_limit: "40 mg every other week",
    notes: "Reference biologic policy with biosimilar-first step requirement.",
  },
  {
    id: "uhc-humira",
    payer_id: "uhc",
    drug_name: "Humira",
    coverage_status: "pa_required",
    policy_version: "v2",
    effective_date: "2026-04-02",
    prior_auth_required: true,
    step_therapy: true,
    quantity_limit: "40 mg every other week",
    notes: "Coverage may require trial of biosimilar first.",
  },
  {
    id: "cigna-keytruda",
    payer_id: "cigna",
    drug_name: "Keytruda",
    coverage_status: "covered",
    policy_version: "v1",
    effective_date: "2026-04-01",
    prior_auth_required: true,
    step_therapy: false,
    quantity_limit: "Per oncology regimen",
    notes: "Oncology policy by tumor type and biomarker criteria.",
  },
];