import type { PolicyDocument } from "./types";

// Static seed data for client-side rendering on pages that
// haven't been connected to Supabase yet (search, compare, dashboard).
// Policy Library uses Supabase directly — this is NOT shown there.
export const SEED_POLICIES: PolicyDocument[] = [
  // Humira — aetna
  {
    id: "seed-001", payer_id: "aetna", drug_id: "adalimumab",
    drug_name: "Humira", drug_generic: "adalimumab", j_code: "J0135",
    coverage_status: "covered", formulary_tier: "preferred_specialty",
    prior_auth_required: true,
    prior_auth_criteria: "Patient must have moderate to severe RA (DAS28 >3.2) and failed ≥1 DMARD for 3 months.",
    step_therapy: true, step_therapy_drugs: ["methotrexate", "sulfasalazine"],
    site_of_care: null, indications: ["RA", "PsA", "CD", "UC", "AS"],
    quantity_limit: "40mg every 2 weeks or 80mg every 4 weeks",
    clinical_criteria: "CDAI >10 or DAS28 >3.2", renewal_period: "12 months",
    policy_version: "v4.1", effective_date: "2025-01-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: ["coverage_status", "prior_auth_criteria"],
  },
  // Humira — uhc
  {
    id: "seed-002", payer_id: "uhc", drug_id: "adalimumab",
    drug_name: "Humira", drug_generic: "adalimumab", j_code: "J0135",
    coverage_status: "covered", formulary_tier: "preferred_specialty",
    prior_auth_required: true,
    prior_auth_criteria: "Patient must have moderate to severe RA (DAS28 >3.2) and failed ≥1 DMARD for 3 months.",
    step_therapy: true, step_therapy_drugs: ["methotrexate", "sulfasalazine"],
    site_of_care: null, indications: ["RA", "PsA", "CD", "UC", "AS"],
    quantity_limit: "40mg every 2 weeks or 80mg every 4 weeks",
    clinical_criteria: "CDAI >10 or DAS28 >3.2", renewal_period: "12 months",
    policy_version: "v4.2", effective_date: "2025-04-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Humira — cigna
  {
    id: "seed-003", payer_id: "cigna", drug_id: "adalimumab",
    drug_name: "Humira", drug_generic: "adalimumab", j_code: "J0135",
    coverage_status: "covered", formulary_tier: "non_preferred",
    prior_auth_required: true,
    prior_auth_criteria: "Patient must have moderate to severe RA (DAS28 >3.2) and failed ≥1 DMARD for 3 months.",
    step_therapy: true, step_therapy_drugs: ["methotrexate", "sulfasalazine"],
    site_of_care: null, indications: ["RA", "PsA", "CD", "UC", "AS"],
    quantity_limit: "40mg every 2 weeks or 80mg every 4 weeks",
    clinical_criteria: "CDAI >10 or DAS28 >3.2", renewal_period: "12 months",
    policy_version: "v3.2", effective_date: "2025-07-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Humira — bcbs-tx
  {
    id: "seed-004", payer_id: "bcbs-tx", drug_id: "adalimumab",
    drug_name: "Humira", drug_generic: "adalimumab", j_code: "J0135",
    coverage_status: "covered", formulary_tier: "preferred_specialty",
    prior_auth_required: false,
    prior_auth_criteria: "",
    step_therapy: false, step_therapy_drugs: [],
    site_of_care: null, indications: ["RA", "PsA", "CD", "UC", "AS"],
    quantity_limit: "40mg every 2 weeks or 80mg every 4 weeks",
    clinical_criteria: null, renewal_period: null,
    policy_version: "v4.0", effective_date: "2025-01-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Keytruda — aetna
  {
    id: "seed-005", payer_id: "aetna", drug_id: "pembrolizumab",
    drug_name: "Keytruda", drug_generic: "pembrolizumab", j_code: "J9271",
    coverage_status: "covered", formulary_tier: "preferred_specialty",
    prior_auth_required: true,
    prior_auth_criteria: "Patient must have PD-L1 expression ≥1% (TPS) confirmed by FDA-approved test. ECOG PS 0–1.",
    step_therapy: false, step_therapy_drugs: [],
    site_of_care: "Outpatient infusion center or oncology clinic only",
    indications: ["NSCLC", "HNSCC", "TNBC", "CRC", "GC"],
    quantity_limit: null, clinical_criteria: "PD-L1 TPS ≥1%", renewal_period: "12 months",
    policy_version: "v4.2", effective_date: "2025-04-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Keytruda — uhc
  {
    id: "seed-006", payer_id: "uhc", drug_id: "pembrolizumab",
    drug_name: "Keytruda", drug_generic: "pembrolizumab", j_code: "J9271",
    coverage_status: "covered", formulary_tier: "preferred_specialty",
    prior_auth_required: false,
    prior_auth_criteria: "",
    step_therapy: false, step_therapy_drugs: [],
    site_of_care: "Outpatient infusion center or oncology clinic only",
    indications: ["NSCLC", "HNSCC", "TNBC", "CRC", "GC"],
    quantity_limit: null, clinical_criteria: "PD-L1 TPS ≥1%", renewal_period: null,
    policy_version: "v3.1", effective_date: "2025-01-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Keytruda — cigna
  {
    id: "seed-007", payer_id: "cigna", drug_id: "pembrolizumab",
    drug_name: "Keytruda", drug_generic: "pembrolizumab", j_code: "J9271",
    coverage_status: "covered", formulary_tier: "non_specialty",
    prior_auth_required: true,
    prior_auth_criteria: "Patient must have PD-L1 expression ≥1% (TPS) confirmed by FDA-approved test.",
    step_therapy: false, step_therapy_drugs: [],
    site_of_care: "Outpatient infusion center or oncology clinic only",
    indications: ["NSCLC", "HNSCC", "TNBC", "CRC", "GC"],
    quantity_limit: null, clinical_criteria: "PD-L1 TPS ≥1%", renewal_period: "12 months",
    policy_version: "v4.0", effective_date: "2025-07-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Keytruda — bcbs-tx
  {
    id: "seed-008", payer_id: "bcbs-tx", drug_id: "pembrolizumab",
    drug_name: "Keytruda", drug_generic: "pembrolizumab", j_code: "J9271",
    coverage_status: "covered", formulary_tier: "non_preferred",
    prior_auth_required: true,
    prior_auth_criteria: "Patient must have PD-L1 expression ≥1% (TPS). For first-line, PD-L1 ≥50%.",
    step_therapy: false, step_therapy_drugs: [],
    site_of_care: "Outpatient infusion center or oncology clinic only",
    indications: ["NSCLC", "HNSCC", "TNBC"],
    quantity_limit: null, clinical_criteria: "PD-L1 TPS ≥1%", renewal_period: "12 months",
    policy_version: "v4.1", effective_date: "2025-04-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: ["indications"],
  },
  // Dupixent — aetna
  {
    id: "seed-009", payer_id: "aetna", drug_id: "dupilumab",
    drug_name: "Dupixent", drug_generic: "dupilumab", j_code: "J0173",
    coverage_status: "covered", formulary_tier: "preferred_specialty",
    prior_auth_required: true,
    prior_auth_criteria: "Moderate-to-severe atopic dermatitis (IGA ≥3 or EASI ≥16) with inadequate response to topical corticosteroids for ≥4 weeks.",
    step_therapy: true, step_therapy_drugs: ["topical corticosteroids", "cyclosporine"],
    site_of_care: null, indications: ["AD", "Asthma", "CRSwNP", "EoE"],
    quantity_limit: null, clinical_criteria: null, renewal_period: "12 months",
    policy_version: "v3.2", effective_date: "2025-10-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Dupixent — uhc
  {
    id: "seed-010", payer_id: "uhc", drug_id: "dupilumab",
    drug_name: "Dupixent", drug_generic: "dupilumab", j_code: "J0173",
    coverage_status: "covered", formulary_tier: "non_specialty",
    prior_auth_required: true,
    prior_auth_criteria: "Moderate-to-severe atopic dermatitis (IGA ≥3 or EASI ≥16) with inadequate response to topical corticosteroids for ≥4 weeks.",
    step_therapy: true, step_therapy_drugs: ["topical corticosteroids", "cyclosporine"],
    site_of_care: null, indications: ["AD", "Asthma", "CRSwNP", "EoE"],
    quantity_limit: null, clinical_criteria: null, renewal_period: "12 months",
    policy_version: "v4.1", effective_date: "2025-04-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Dupixent — cigna (not covered)
  {
    id: "seed-011", payer_id: "cigna", drug_id: "dupilumab",
    drug_name: "Dupixent", drug_generic: "dupilumab", j_code: "J0173",
    coverage_status: "not_covered", formulary_tier: "not_covered",
    prior_auth_required: false,
    prior_auth_criteria: "",
    step_therapy: false, step_therapy_drugs: [],
    site_of_care: null, indications: ["AD"],
    quantity_limit: null, clinical_criteria: null, renewal_period: null,
    policy_version: "v3.1", effective_date: "2025-07-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: ["coverage_status"],
  },
  // Dupixent — bcbs-tx
  {
    id: "seed-012", payer_id: "bcbs-tx", drug_id: "dupilumab",
    drug_name: "Dupixent", drug_generic: "dupilumab", j_code: "J0173",
    coverage_status: "covered", formulary_tier: "non_preferred",
    prior_auth_required: true,
    prior_auth_criteria: "Moderate-to-severe atopic dermatitis with inadequate topical response.",
    step_therapy: true, step_therapy_drugs: ["topical corticosteroids"],
    site_of_care: null, indications: ["AD", "Asthma", "CRSwNP"],
    quantity_limit: null, clinical_criteria: null, renewal_period: "12 months",
    policy_version: "v4.0", effective_date: "2025-01-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Stelara — aetna
  {
    id: "seed-013", payer_id: "aetna", drug_id: "ustekinumab",
    drug_name: "Stelara", drug_generic: "ustekinumab", j_code: "J3357",
    coverage_status: "covered", formulary_tier: "preferred_specialty",
    prior_auth_required: true,
    prior_auth_criteria: "For CD/UC: failed or intolerant to conventional therapy and ≥1 anti-TNF agent.",
    step_therapy: true, step_therapy_drugs: ["methotrexate", "TNF inhibitor"],
    site_of_care: null, indications: ["PsO", "PsA", "CD", "UC"],
    quantity_limit: null, clinical_criteria: null, renewal_period: "12 months",
    policy_version: "v4.2", effective_date: "2025-04-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Stelara — uhc
  {
    id: "seed-014", payer_id: "uhc", drug_id: "ustekinumab",
    drug_name: "Stelara", drug_generic: "ustekinumab", j_code: "J3357",
    coverage_status: "covered", formulary_tier: "non_specialty",
    prior_auth_required: true,
    prior_auth_criteria: "For CD/UC: failed or intolerant to conventional therapy and ≥1 anti-TNF agent.",
    step_therapy: true, step_therapy_drugs: ["methotrexate", "TNF inhibitor"],
    site_of_care: null, indications: ["PsO", "PsA", "CD", "UC"],
    quantity_limit: null, clinical_criteria: null, renewal_period: "12 months",
    policy_version: "v3.2", effective_date: "2025-01-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Stelara — cigna (not covered)
  {
    id: "seed-015", payer_id: "cigna", drug_id: "ustekinumab",
    drug_name: "Stelara", drug_generic: "ustekinumab", j_code: "J3357",
    coverage_status: "not_covered", formulary_tier: "not_covered",
    prior_auth_required: false,
    prior_auth_criteria: "",
    step_therapy: false, step_therapy_drugs: [],
    site_of_care: null, indications: [],
    quantity_limit: null, clinical_criteria: null, renewal_period: null,
    policy_version: "v3.1", effective_date: "2025-07-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: ["coverage_status"],
  },
  // Stelara — bcbs-tx
  {
    id: "seed-016", payer_id: "bcbs-tx", drug_id: "ustekinumab",
    drug_name: "Stelara", drug_generic: "ustekinumab", j_code: "J3357",
    coverage_status: "covered", formulary_tier: "preferred_specialty",
    prior_auth_required: true,
    prior_auth_criteria: "For CD/UC: failed or intolerant to conventional therapy and ≥1 anti-TNF agent.",
    step_therapy: true, step_therapy_drugs: ["methotrexate", "TNF inhibitor"],
    site_of_care: null, indications: ["PsO", "PsA", "CD", "UC"],
    quantity_limit: null, clinical_criteria: null, renewal_period: "12 months",
    policy_version: "v4.1", effective_date: "2025-04-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Enbrel — aetna
  {
    id: "seed-017", payer_id: "aetna", drug_id: "etanercept",
    drug_name: "Enbrel", drug_generic: "etanercept", j_code: "J1438",
    coverage_status: "covered", formulary_tier: "non_preferred",
    prior_auth_required: true,
    prior_auth_criteria: "Active moderate-to-severe RA (≥6 tender and ≥6 swollen joints) and inadequate response to methotrexate at therapeutic doses for ≥3 months.",
    step_therapy: true, step_therapy_drugs: ["methotrexate", "hydroxychloroquine"],
    site_of_care: null, indications: ["RA", "PsA", "PsO", "AS", "JIA"],
    quantity_limit: null, clinical_criteria: null, renewal_period: "12 months",
    policy_version: "v4.0", effective_date: "2025-01-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Enbrel — uhc
  {
    id: "seed-018", payer_id: "uhc", drug_id: "etanercept",
    drug_name: "Enbrel", drug_generic: "etanercept", j_code: "J1438",
    coverage_status: "covered", formulary_tier: "preferred_specialty",
    prior_auth_required: false,
    prior_auth_criteria: "",
    step_therapy: false, step_therapy_drugs: [],
    site_of_care: null, indications: ["RA", "PsA", "PsO", "AS", "JIA"],
    quantity_limit: null, clinical_criteria: null, renewal_period: null,
    policy_version: "v4.2", effective_date: "2025-04-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Enbrel — cigna
  {
    id: "seed-019", payer_id: "cigna", drug_id: "etanercept",
    drug_name: "Enbrel", drug_generic: "etanercept", j_code: "J1438",
    coverage_status: "covered", formulary_tier: "non_specialty",
    prior_auth_required: true,
    prior_auth_criteria: "Active moderate-to-severe RA and inadequate response to methotrexate.",
    step_therapy: true, step_therapy_drugs: ["methotrexate"],
    site_of_care: null, indications: ["RA", "PsA", "PsO", "AS"],
    quantity_limit: null, clinical_criteria: null, renewal_period: "12 months",
    policy_version: "v3.2", effective_date: "2025-07-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
  // Enbrel — bcbs-tx
  {
    id: "seed-020", payer_id: "bcbs-tx", drug_id: "etanercept",
    drug_name: "Enbrel", drug_generic: "etanercept", j_code: "J1438",
    coverage_status: "covered", formulary_tier: "non_preferred",
    prior_auth_required: true,
    prior_auth_criteria: "Active moderate-to-severe RA and inadequate response to methotrexate at therapeutic doses.",
    step_therapy: true, step_therapy_drugs: ["methotrexate", "hydroxychloroquine"],
    site_of_care: null, indications: ["RA", "PsA", "PsO", "AS", "JIA"],
    quantity_limit: null, clinical_criteria: null, renewal_period: "12 months",
    policy_version: "v4.1", effective_date: "2025-04-01",
    source_pdf_url: null, extracted_at: "2026-04-01T00:00:00Z",
    changed_fields: [],
  },
];
